In [176]:
import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')

# gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=8048)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)

1 Physical GPUs, 1 Logical GPUs


# BCI Comprehensive Data Alignment

# Section 1: Get epochs 

In [177]:
import mne
import numpy as np
from mne.datasets import eegbci
import matplotlib.pyplot as plt
from os import listdir
from mne.channels import make_standard_montage
from BCIAllFunction import BCIFuntions
from main_utilize import Unicorn

target_class = ["Left", "Right"] 
AllBCIClass = Unicorn(selectclass = target_class, desired_fz = 128, ch_pick = ['Fz','C3','Cz','C4','Pz'])

target_data_0 = "AJpang" #this subject will be test_set otherwise are train_set
calibrate_size = 20 # (trial)

condition_wLTL = "EA"
train_svm = True    

all_data = ["pipo","NutF8","AJpang","Aoomim","voen","pipo_HCI","Kawin"]

EEG_data = AllBCIClass.GetRawEDF(target_subjects= all_data, condition="Offline_Experiment") #Input data -> 250Hz with 6-32 Hz filtered + CAR

Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the instance is already 128.0, returning unmodified.
Sampling frequency of the

In [178]:
EEG_Epochs = AllBCIClass.GetEpoch(EEG_data ,tmin= -2.0, tmax= 6.0, crop = (0,4) ,baseline= (-0.5,0.0), band_pass=(6,32),trial_removal_th = 100)
calibrate_size = calibrate_size / EEG_Epochs[target_data_0]['Raw_Epoch'].shape[0]

Used Annotations descriptions: ['OVTK_GDF_Cross_On_Screen', 'OVTK_GDF_Left', 'OVTK_GDF_Right', 'OVTK_GDF_Tongue', 'OVTK_GDF_Up']
Used Annotations descriptions: ['OVTK_GDF_Cross_On_Screen', 'OVTK_GDF_Left', 'OVTK_GDF_Right', 'OVTK_GDF_Tongue', 'OVTK_GDF_Up']
NutF8 -104.04128118288183 6
NutF8 86.93096401141673 6
NutF8 -104.31893713412965 11
NutF8 91.19854783269322 11
Used Annotations descriptions: ['OVTK_GDF_Cross_On_Screen', 'OVTK_GDF_Left', 'OVTK_GDF_Right', 'OVTK_GDF_Tongue', 'OVTK_GDF_Up']
Used Annotations descriptions: ['OVTK_GDF_Cross_On_Screen', 'OVTK_GDF_Left', 'OVTK_GDF_Right', 'OVTK_GDF_Tongue', 'OVTK_GDF_Up']
Used Annotations descriptions: ['OVTK_GDF_Cross_On_Screen', 'OVTK_GDF_Left', 'OVTK_GDF_Right', 'OVTK_GDF_Tongue', 'OVTK_GDF_Up']


c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()
c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()
c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()
c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()
c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: T

voen -1044.3428689131774 1
voen 694.2336071556814 1
voen -1039.3090824149497 2
voen 1021.4912607644604 2
voen -952.1519349924243 3
voen 1248.5144240059017 3
voen -1608.9284132711775 4
voen 965.6585709158061 4
voen -1275.969071501411 5
voen 920.2083808985063 5
voen -1051.3249792289928 6
voen 1127.088200732215 6
voen -1118.8426560634346 7
voen 1023.6485819775758 7
voen -1110.100150071416 8
voen 1582.339498768439 8
voen -1366.6406708885727 9
voen 1388.9085742043058 9
voen -1394.9850131738478 10
voen 1248.7950534581623 10
voen -1058.9534477025018 11
voen 1235.0663150799874 11
voen -909.8656260370225 12
voen 1493.0761987368824 12
voen -1314.4848276191683 13
voen 1633.0580035876765 13
voen -1545.6211509595928 14
voen 1774.5966791494222 14
voen -1175.509996496856 15
voen 1226.8960635721676 15
voen -1299.1713236171295 16
voen 700.759425551083 16
voen -1363.6523253095506 18
voen 722.045752907745 18
voen -635.5815560003313 19
voen 780.722404087494 19
voen -1445.0522911441922 20
voen 756.72940135

c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()
c:\git\BCI_MI_Study\main_utilize.py:97: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  train_data = EEG_epoch[key_subs]['Raw_Epoch'].get_data()


# Section 2: Apply Data Alignment on RAW data

Note: After performing EA for all subjects, they share the same mean covariance matrix, i.e., the distances between the mean covariance matrices of different subjects are minimized (they become zero), and hence data distributions from different subjects become more similar.

In [179]:
AllBCIClass.ComputeEA(EEG_Epochs, target_subject= target_data_0, calibrate_size=calibrate_size)
if calibrate_size != 0:
    target_data = target_data_0 + "_test"

In [180]:
target_data

'AJpang_test'

# Section 3 : CSP

In [181]:
CSP3D_Epoch = AllBCIClass.computeCSPFeatures(EEG_Epochs, target_subject = target_data, transform_into="csp_space")

Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.


# Section 4 : T-SNE Plot

In [182]:
# AllBCIClass.TSNE_Plot(CSP2D_Epoch, target_subject= target_data)

# Section 5: Model Training

# CSP+wLTL 

In [183]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GRU, Dense, GlobalAveragePooling1D, TimeDistributed, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy

# Custom loss function
class CustomLossLL1(tf.keras.losses.Loss):
    def __init__(self, lambda_t, model):
        super().__init__()
        self.lambda_t = lambda_t
        self.cross_entropy = CategoricalCrossentropy()
        self.model = model

    def call(self, y_true, y_pred):
        ce_loss = self.cross_entropy(y_true, y_pred)
        ws = self.get_weights_from_model()
        reg_term = self.regularization_term(ws)
        return ce_loss + self.lambda_t * reg_term

    def get_weights_from_model(self):
        model_weights = []
        for layer in self.model.layers:
            if len(layer.get_weights()) > 0:
                model_weights.append(layer.get_weights()[0])

        # print(model_weights[-1])
        # print(aaa)
        return model_weights[-1]

    def regularization_term(self, ws):
        reg_term = tf.pow(tf.norm(ws, ord='euclidean'),2)
        return reg_term


# Custom training loop
def custom_train_step(model, optimizer, x, y, custom_loss):
    with tf.GradientTape() as tape:
        y_pred = model(x, training=True) # Perform a forward pass and compute the predictions
        loss = custom_loss(y, y_pred) # Compute the custom loss
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss


def train_weight_LL(X_train, y_train, lambd, num_tier=10, learning_rate = 0.01):
    n_classes = np.unique(y_train).size
    _, sequential_indices = np.unique(y_train, return_inverse=True)
    y_one_hot = tf.keras.utils.to_categorical(sequential_indices, num_classes=n_classes)

    lambda_t = lambd  # Regularization parameter

    model = Sequential([
        # 1D Convolution Layer
        Conv1D(32, kernel_size=3, strides=1, activation='relu', input_shape=(513, 5)),
        # Max Pooling Layer
        MaxPooling1D(pool_size=3, strides=2),
        Dropout(0.5),
        # Second 1D Convolution Layer
        Conv1D(64, kernel_size=3, strides=1, activation='relu'),
        # Second Max Pooling Layer
        MaxPooling1D(pool_size=3, strides=2),
        Dropout(0.5),
        # GRU Layer
        GRU(5, return_sequences=True),
        # Time Distributed Dense Layer
        TimeDistributed(Dense(5, activation='relu')),
        # Global Average Pooling Layer
        GlobalAveragePooling1D(),
        # Dense Layer for output (adjusted for binary classification)
        # Dense(15, activation='relu'),
        # Dense(5, activation='relu'),
        Dense(n_classes, activation='softmax')
    ])

    # Compile the model
    optimizer = Adam(learning_rate)
    custom_loss = CustomLossLL1(lambda_t, model)

    # Custom training loop
    epochs = num_tier
    lowest_loss = float('inf')
    best_weights = None
    for epoch in range(epochs):
        loss = custom_train_step(model, optimizer, X_train, y_one_hot, custom_loss)
        loss_value = loss.numpy()
        if loss_value < lowest_loss:
            lowest_loss = loss_value
            best_weights = [layer.get_weights() for layer in model.layers]

        if epoch % 20 == 0:
            print(f"Epoch {epoch}, Loss: {loss.numpy()}")

    return best_weights[-1], lowest_loss

def build_clf_params(data, target_subjects ,condition):

    for sub in data.keys():
        if (sub  != target_subjects) and  (sub != target_data_0): #Don't apply weight to target subject
            # Where the tranining data is stored
            if condition == "noEA":
                X = data[sub]['Raw_csp']
                y = data[sub]['Raw_csp_label']
                store_ws = 'ws_Raw'

            else:
                X = data[sub]['EA_csp']
                y = data[sub]['EA_csp_label']
                store_ws = 'ws_EA'

            X = np.transpose(X, (0, 2, 1))

            weights, loss = train_weight_LL(X_train=X, y_train=y, lambd= 0.1, num_tier=1000, learning_rate= 0.005)
            print("weights of ", str(sub), ": ", weights)
            print("Lowest loss of ", str(sub), ": ", loss)
            data[sub][store_ws] = weights

build_clf_params(CSP3D_Epoch, target_subjects= target_data ,condition = "EA")

Epoch 0, Loss: 0.9735111594200134
Epoch 20, Loss: 0.7829979658126831
Epoch 40, Loss: 0.6526635885238647
Epoch 60, Loss: 0.6830465197563171
Epoch 80, Loss: 0.7027799487113953
Epoch 100, Loss: 0.7215807437896729
Epoch 120, Loss: 0.7393640875816345
Epoch 140, Loss: 0.7438787817955017
Epoch 160, Loss: 0.8349280953407288
Epoch 180, Loss: 0.8059924840927124
Epoch 200, Loss: 0.8029522895812988
Epoch 220, Loss: 0.811596691608429
Epoch 240, Loss: 0.8313252329826355
Epoch 260, Loss: 0.8427411317825317
Epoch 280, Loss: 0.8608443737030029
Epoch 300, Loss: 0.9576284289360046
Epoch 320, Loss: 0.8698269724845886
Epoch 340, Loss: 0.8830923438072205
Epoch 360, Loss: 1.0043046474456787
Epoch 380, Loss: 0.8840739130973816
Epoch 400, Loss: 0.8917523622512817
Epoch 420, Loss: 0.8967113494873047
Epoch 440, Loss: 0.9072285294532776
Epoch 460, Loss: 0.9139732122421265
Epoch 480, Loss: 0.9178776144981384
Epoch 500, Loss: 0.9282225370407104
Epoch 520, Loss: 0.9893081784248352
Epoch 540, Loss: 0.9702335596084595

NOTE:
Weights (array): These are the parameters that the model learns during training. They represent the strength of the connections between neurons. The shape of the weights array is (input_dim, output_dim).

Biases (array): These are additional parameters that are added to the outputs of each layer. The shape of the biases array is (output_dim,).

In [184]:
CSP3D_Epoch['pipo'].keys()

dict_keys(['Raw_csp', 'Raw_csp_label', 'EA_csp', 'EA_csp_label', 'ws_EA'])

In [185]:
# First define the kl divergence
def KL_div(P, Q):
    # First convert to np array
    P = np.array(P)
    Q = np.array(Q)

    # Then compute their means, datain shape of samples x feat
    mu_P = np.mean(np.mean(P, axis=0), axis=1)
    mu_Q = np.mean(np.mean(Q, axis=0), axis=1)    
    
    # Compute their covariance
    sigma_P = np.cov(np.mean(P, axis = 0))
    sigma_Q = np.cov(np.mean(Q, axis = 0))

    print(mu_P.shape)
    print(sigma_P.shape)

    # Check the condition number
    if np.isnan(sigma_Q).any():
        pass
    else:
        condition_number = np.linalg.cond(sigma_Q)
        # If the condition number is too high, use a regularized version
        if condition_number > 1e10:  # Threshold to decide if it's ill-conditioned
            print("add small epsilon")
            epsilon = 1e-5  # Small regularization value
            sigma_Q += epsilon * np.eye(sigma_Q.shape[0])
            sigma_P += epsilon * np.eye(sigma_P.shape[0])

    diff = mu_Q-mu_P

    inv_sigma_Q = np.linalg.inv(sigma_Q)

    term1 = np.dot(np.dot(diff.T, inv_sigma_Q), diff)

    # Calculate the trace term trace(Sigma_Q^{-1} * Sigma_P)
    term2 = np.trace(np.dot(inv_sigma_Q, sigma_P))
    
    # Calculate the determinant term ln(det(Sigma_P) / det(Sigma_Q))
    det_sigma0 = np.linalg.det(sigma_P)
    det_sigma1 = np.linalg.det(sigma_Q)
    epsilon = 1e-10 
    term3 = np.log((det_sigma0+epsilon) / (det_sigma1+epsilon))
    
    # Dimensionality of the data
    K = mu_P.shape[0]
    
    # KL divergence
    kl_div = 0.5 * (term1 + term2 - term3 - K)
    
    return kl_div


# Compute kl divergence of target subject to each source subject
def compute_all_kl_div(data, target_subjects , condition):
    '''
    Parameter:
    data, is the whole data containing target and source data
    '''
    kl_div_score = []

    if condition == "noEA":
        target_data = 'Raw_csp'
        label_name = 'Raw_csp_label'
        
    else:
        target_data = 'EA_csp'
        label_name = 'EA_csp_label'
        
    # cal P from target data
    label_tgt =  data[target_subjects][label_name]
    P_left =  data[target_subjects][target_data][np.where(label_tgt == 0)]
    P_right = data[target_subjects][target_data][np.where(label_tgt == 1)]
    P_non = data[target_subjects][target_data][np.where(label_tgt == 2)]
    P_feet = data[target_subjects][target_data][np.where(label_tgt == 3)]

    tgt_data = target_subjects + "_test"

    #cal Q from each source subject
    for sub in data.keys():
        if (sub != target_subjects) and (sub != tgt_data):
            print(sub)
            label_src =  data[sub][label_name]
            Q_left =  data[sub][target_data][np.where(label_src == 0)]
            Q_right = data[sub][target_data][np.where(label_src == 1)]
            Q_non = data[sub][target_data][np.where(label_src == 2)]
            Q_feet = data[sub][target_data][np.where(label_src == 3)]

            kl_left = KL_div(P_left, Q_left)
            kl_right = KL_div(P_right, Q_right)
            kl_non = KL_div(P_non, Q_non)
            kl_feet = KL_div(P_feet, Q_feet)

            kl_div_temp = [kl_left, kl_right, kl_non, kl_feet]
            kl_div_score.append(kl_div_temp)

    data[target_subjects]['kl_div'] = kl_div_score

compute_all_kl_div(CSP3D_Epoch, target_subjects=target_data_0 ,condition = condition_wLTL) #target_sub for cal KL is calibrate set

pipo
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
NutF8
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
Aoomim
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
voen
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
pipo_HCI
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
Kawin
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)
(5,)
(5, 5)


c:\Users\pipo_\miniconda3\envs\tfgpu\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\pipo_\miniconda3\envs\tfgpu\lib\site-packages\numpy\core\_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
c:\Users\pipo_\miniconda3\envs\tfgpu\lib\site-packages\numpy\linalg\linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [186]:
np.array(CSP3D_Epoch[target_data_0]['kl_div'])

array([[ 6.47236002,  6.17698312,         nan,         nan],
       [ 5.12044435,  5.53021688,         nan,         nan],
       [ 5.0595023 ,  4.88562584,         nan,         nan],
       [ 2.92761665,  2.48969207,         nan,         nan],
       [14.18048882, 12.08185933,         nan,         nan],
       [ 5.78852563,  4.92425466,         nan,         nan]])

In [187]:
def compute_similarity_weights(data, target_subjects):
    kl = data[target_subjects]['kl_div']
    KL_inv_left = []
    KL_inv_right = []
    KL_inv_non = []
    KL_inv_feet = []

    alpha_s = []
    eps = 0.0001
    
    #equation (9)
    for val in kl:
        if val != 0: 
            KL_inv_left.append(1/((val[0] + eps)**4))
            KL_inv_right.append(1/((val[1] + eps)**4))
            KL_inv_non.append(1/((val[2] + eps)**4))
            KL_inv_feet.append(1/((val[3] + eps)**4))

    print(KL_inv_left)
    print(KL_inv_right)
    
    for i in range(0,len(KL_inv_left)):
        temp = [KL_inv_left[i]/sum(KL_inv_left), KL_inv_right[i]/sum(KL_inv_right), KL_inv_non[i]/sum(KL_inv_non), KL_inv_feet[i]/sum(KL_inv_feet)]
        alpha_s.append(temp)

    alpha_s = np.array(alpha_s)
    print(np.array(alpha_s[:, ~np.isnan(alpha_s).any(axis=0)]))
                
    data[target_subjects]['alpha_s'] = alpha_s[:, ~np.isnan(alpha_s).any(axis=0)]

compute_similarity_weights(CSP3D_Epoch, target_subjects=target_data_0)

[0.0005698000652301266, 0.001454572836220458, 0.0015259295200230182, 0.013610805628169962, 2.4729933138061944e-05, 0.0008906316962083242]
[0.0006868568265086649, 0.0010690547169918685, 0.0017550262963522717, 0.026022420086865915, 4.6929996551302e-05, 0.001700602069849489]
[[0.03152165 0.02195771]
 [0.08046775 0.03417597]
 [0.08441524 0.05610538]
 [0.75295707 0.83189513]
 [0.00136807 0.00150028]
 [0.04927022 0.05436553]]


In [188]:
def compute_ETL_and_mu_ws(data, target_subjects, condition):

    mu_ws = 0
    temp_ws = 0

    if condition == "noEA":
        ws_name = 'ws_Raw'
    elif condition == "stack":
        ws_name = 'ws_stack'
    else:
        ws_name = 'ws_EA'

    alpha_s = np.array(data[target_subjects]['alpha_s'])

    tgt_data = target_subjects + "_test"
    index_count = 0

    for sub in data.keys():
        if (sub != target_subjects) and (sub != tgt_data):
            ws = data[sub][ws_name][0]
            mu_ws += ws * alpha_s[index_count]
            index_count += 1

    print(np.array(mu_ws))

    index_count = 0
    for sub in data.keys():
        if (sub != target_subjects) and (sub != tgt_data):
            ws = data[sub][ws_name][0]
            ws_min_mu = np.dot(((ws * alpha_s[index_count]) - mu_ws), np.transpose((ws * alpha_s[index_count]) - mu_ws))
            temp_ws += ws_min_mu #equation (11)
            index_count += 1

    print(np.array(temp_ws))
    
    den = temp_ws
    nom = np.trace(temp_ws) #Return the sum along diagonals of the array.
    Sigma_TL = den/nom

    data[target_subjects]['Sigma_TL'] = Sigma_TL
    data[target_subjects]['mu_ws'] = mu_ws

compute_ETL_and_mu_ws(CSP3D_Epoch, target_subjects = target_data_0, condition=condition_wLTL)

[[-0.53544679  0.60108232]
 [ 0.74979213 -0.86555099]
 [-0.54470348  0.51379199]
 [ 0.47489301 -0.37888202]
 [-0.07478961  0.63812525]]
[[ 3.3335606  -4.55123986  3.06046163 -2.4635422   2.10020099]
 [-4.55123986  6.33327086 -4.17377271  3.34468277 -3.01181776]
 [ 3.06046163 -4.17377271  2.83241262 -2.3012059   1.81696332]
 [-2.4635422   3.34468277 -2.3012059   1.907175   -1.3575755 ]
 [ 2.10020099 -3.01181776  1.81696332 -1.3575755   2.08625343]]


In [189]:
print(np.array(CSP3D_Epoch[target_data_0]['Sigma_TL']).shape)
print(np.array(CSP3D_Epoch[target_data_0]['mu_ws']).shape)

(5, 5)
(5, 2)


# Test ACC with target subject

In [190]:
# Custom loss function
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GRU, Dense, GlobalAveragePooling1D, TimeDistributed, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

class CustomLossLL2(tf.keras.losses.Loss):
    def __init__(self, lambda_t, model, mu, sigma_TL):
        super().__init__()
        self.lambda_t = lambda_t
        self.cross_entropy = CategoricalCrossentropy()
        self.model = model
        self.mu = tf.convert_to_tensor(mu, dtype=tf.float32)
        self.sigma_TL = tf.convert_to_tensor(sigma_TL, dtype=tf.float32)

    def call(self, y_true, y_pred):
        ce_loss = self.cross_entropy(y_true, y_pred)
        wt = self.get_weights_from_model()
        reg_term = self.regularization_term(wt)

        return ce_loss + (self.lambda_t * tf.linalg.matmul(reg_term, wt))

    def get_weights_from_model(self):
        model_weights = []
        for layer in self.model.layers:
            if len(layer.get_weights()) > 0:
                model_weights.append(layer.get_weights()[0])
        return model_weights[-1]

    def regularization_term(self, wt):
        diff = wt - self.mu
        reg_term = 0.5 * tf.linalg.matmul(tf.linalg.matmul(tf.linalg.inv(self.sigma_TL), diff), tf.transpose(diff))
        reg_term += 0.5 * tf.math.log(tf.linalg.det(self.sigma_TL))
        return reg_term


# Custom training loop
def custom_train_step(model, optimizer, x, y, custom_loss):
    with tf.GradientTape() as tape:
        y_pred = model(x, training=True) # Perform a forward pass and compute the predictions
        loss = custom_loss(y, y_pred) # Compute the custom loss
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss


def train_weight_LL2(X_train, y_train, lambd, mu, sigma_TL, num_tier=10, learning_rate = 0.01):
    n_classes = np.unique(y_train).size
    _, sequential_indices = np.unique(y_train, return_inverse=True)
    y_one_hot = tf.keras.utils.to_categorical(sequential_indices, num_classes=n_classes)

    lambda_t = lambd  # Regularization parameter

    model = Sequential([
        # 1D Convolution Layer
        Conv1D(32, kernel_size=3, strides=1, activation='relu', input_shape=(513, 5)),
        # Max Pooling Layer
        MaxPooling1D(pool_size=3, strides=2),
        Dropout(0.5),
        # Second 1D Convolution Layer
        Conv1D(64, kernel_size=3, strides=1, activation='relu'),
        # Second Max Pooling Layer
        MaxPooling1D(pool_size=3, strides=2),
        Dropout(0.5),
        # GRU Layer
        GRU(5, return_sequences=True),
        # Time Distributed Dense Layer
        TimeDistributed(Dense(5, activation='relu')),
        # Global Average Pooling Layer
        GlobalAveragePooling1D(),
        # Dense Layer for output (adjusted for binary classification)
        # Dense(15, activation='relu'),
        # Dense(5, activation='relu'),
        Dense(n_classes, activation='softmax')
    ])


    # Compile the model
    optimizer = Adam(learning_rate)
    custom_loss = CustomLossLL2(lambda_t, model, mu, sigma_TL)

    # Custom training loop
    epochs = num_tier
    lowest_loss = float('inf')
    best_weights = None
    best_model = None

    for epoch in range(epochs):
        loss = custom_train_step(model, optimizer, X_train, y_one_hot, custom_loss)
        loss_value = loss.numpy()
        if epoch % 20 == 0:
            print(f"Epoch {epoch}, Loss: {loss.numpy()}")

        if (abs(loss_value) < lowest_loss):
            lowest_loss = abs(loss_value)
            best_model = model
            best_weights = [layer.get_weights() for layer in model.layers]

    return best_model, best_weights[-1], lowest_loss

def GetConfusionMatrix(model, X_train, X_test, y_train, y_test):
    y_pred_prob = model.predict(X_train)
    y_pred = np.argmax(y_pred_prob, axis=1)
    _, y_train = np.unique(y_train, return_inverse=True)

    print("Classification TRAIN DATA \n=======================")
    print(classification_report(y_true= y_train, y_pred=y_pred))
    print("Confusion matrix \n=======================")
    print(confusion_matrix(y_true= y_train, y_pred=y_pred))

    y_pred_prob = model.predict(X_test)
    y_pred = np.argmax(y_pred_prob, axis=1)
    _, y_test = np.unique(y_test, return_inverse=True)

    print("Classification TEST DATA \n=======================")
    print(classification_report(y_true=y_test, y_pred=y_pred))
    print("Confusion matrix \n=======================")
    print(confusion_matrix(y_true=y_test, y_pred=y_pred))

def tgt_test_wLTL(data, target_subjects ,condition):
    tgt_data = target_subjects + "_test"

    if condition == "noEA":
        X = data[target_subjects]['Raw_csp']
        y = data[target_subjects]['Raw_csp_label']
        X_test = data[tgt_data]['Raw_csp']
        y_test = data[tgt_data]['Raw_csp_label']
        store_ws = 'wt_Raw'

    else:
        X = data[target_subjects]['EA_csp']
        y = data[target_subjects]['EA_csp_label']
        X_test = data[tgt_data]['EA_csp']
        y_test = data[tgt_data]['EA_csp_label']
        store_ws = 'wt_EA'

    mu = data[target_subjects]['mu_ws']
    sigma_TL = data[target_subjects]['Sigma_TL']

    X_train = np.transpose(X, (0, 2, 1))
    X_test = np.transpose(X_test, (0, 2, 1))
    y_train = y
    
    model, weights, loss = train_weight_LL2(X_train=X_train, y_train=y_train, mu =mu, sigma_TL=sigma_TL,  lambd= 0.1, num_tier=2000, learning_rate= 0.01)
    print("weights of ", str(target_subjects), ": ", weights)
    print("loss of ", str(target_subjects), ": ", loss)
    data[target_subjects][store_ws] = weights

    GetConfusionMatrix(model, X_train, X_test, y_train, y_test)

tgt_test_wLTL(CSP3D_Epoch, target_subjects= target_data_0 ,condition = condition_wLTL)

Epoch 0, Loss: 39.165245056152344
Epoch 20, Loss: 35.29277801513672
Epoch 40, Loss: 30.965124130249023
Epoch 60, Loss: 27.787982940673828
Epoch 80, Loss: 24.593334197998047
Epoch 100, Loss: 23.135822296142578
Epoch 120, Loss: 23.133907318115234
Epoch 140, Loss: 22.068119049072266
Epoch 160, Loss: 21.345409393310547
Epoch 180, Loss: 20.7058048248291
Epoch 200, Loss: 20.338268280029297
Epoch 220, Loss: 20.014677047729492
Epoch 240, Loss: 20.401535034179688
Epoch 260, Loss: 20.5436954498291
Epoch 280, Loss: 20.005931854248047
Epoch 300, Loss: 19.568714141845703
Epoch 320, Loss: 19.39156723022461
Epoch 340, Loss: 19.294553756713867
Epoch 360, Loss: 19.108665466308594
Epoch 380, Loss: 18.86256217956543
Epoch 400, Loss: 18.711950302124023
Epoch 420, Loss: 18.51485824584961
Epoch 440, Loss: 19.974637985229492
Epoch 460, Loss: 20.318878173828125
Epoch 480, Loss: 19.943838119506836
Epoch 500, Loss: 19.706302642822266
Epoch 520, Loss: 19.666370391845703
Epoch 540, Loss: 19.774526596069336
Epoch 

# noEA + LDA

In [191]:
AllBCIClass.classifyCSP_LDA(EEG_Epochs, target_subjects= target_data, calibrate_data= target_data_0, condition = "noEA")

Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Classification TRAIN DATA 
              precision    recall  f1-score   support

        Left       0.69      0.68      0.68       202
       Right       0.68      0.69      0.68       200

    accuracy                           0.68       402
   macro avg       0.68      0.68      0.68       402
weighted avg       0.68      0.68      0.68       402

Confusion matrix 
[[137  65]
 [ 63 137]]
Classification TEST DATA 
              precision    recall  f1-score   support

        Left       0.50      0.95      0.66        20
       Right       0.50      0.05      0.09        20

    accuracy                           0.50        40
   macro avg 

# noEA + SVM

In [192]:
if train_svm == True:
    AllBCIClass.classifyCSP_SVM(EEG_Epochs, target_subjects= target_data, calibrate_data= target_data_0,condition = "noEA")

Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Best parameters: {'C': 1, 'kernel': 'linear'}
Best cross-validation score: 0.664
Classification TRAIN DATA 
              precision    recall  f1-score   support

        Left       0.67      0.68      0.67       202
       Right       0.67      0.66      0.66       200

    accuracy                           0.67       402
   macro avg       0.67      0.67      0.67       402
weighted avg       0.67      0.67      0.67       402

Confusion matrix 
[[137  65]
 [ 69 131]]
Classification TEST DATA 
              precision    recall  f1-score   support

        Left       0.50      0.95      0.66        20
       Right       0.50      0.05      0.

# EA+LDA

In [193]:
AllBCIClass.classifyCSP_LDA(EEG_Epochs, target_subjects= target_data, calibrate_data= target_data_0, condition = "EA")

Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Classification TRAIN DATA 
              precision    recall  f1-score   support

        Left       0.73      0.73      0.73       202
       Right       0.73      0.72      0.73       200

    accuracy                           0.73       402
   macro avg       0.73      0.73      0.73       402
weighted avg       0.73      0.73      0.73       402

Confusion matrix 
[[148  54]
 [ 55 145]]
Classification TEST DATA 
              precision    recall  f1-score   support

        Left       0.73      0.55      0.63        20
       Right       0.64      0.80      0.71        20

    accuracy                           0.68        40
   macro avg 

In [194]:
if train_svm == True:
    AllBCIClass.classifyCSP_SVM(EEG_Epochs, target_subjects= target_data, calibrate_data= target_data_0,condition = "EA")

Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='info'
    MAG: rank 5 after 0 projectors applied to 5 channels
Reducing data rank from 5 -> 5
Estimating covariance using EMPIRICAL
Done.
Best parameters: {'C': 1, 'kernel': 'rbf'}
Best cross-validation score: 0.721
Classification TRAIN DATA 
              precision    recall  f1-score   support

        Left       0.78      0.77      0.77       202
       Right       0.77      0.78      0.77       200

    accuracy                           0.77       402
   macro avg       0.77      0.77      0.77       402
weighted avg       0.77      0.77      0.77       402

Confusion matrix 
[[155  47]
 [ 45 155]]
Classification TEST DATA 
              precision    recall  f1-score   support

        Left       0.62      0.40      0.48        20
       Right       0.56      0.75      0.64 